# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [4]:
import numpy as np
from numpy.random import randint as ri

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [12]:
mat1 = np.arange(0,9).reshape(3,3)
mat2 = np.arange(0,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)




1st Matrix of random single-digit numbers
----------------------------------------
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
print("\nAddition\n------------------\n", mat1 + mat2)


Addition
------------------
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [29]:
print("\nMultiplication\n------------------\n", mat1.dot(mat2))


Multiplication
------------------
 [[44 74 66]
 [49 84 60]
 [23 53 17]]


In [15]:
print("\nDivision\n------------------\n", mat1/mat2)


Division
------------------
 [[nan  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


C:\Users\Dikshit\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [16]:
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1 - 2*mat2)


Linear combination: 3*A - 2*B
-----------------------------
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[100 101 102]
 [103 104 105]
 [106 107 108]]


In [20]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)


Exponentiation, matrix cubed here
----------------------------------------
 [[  0   1   8]
 [ 27  64 125]
 [216 343 512]]


In [22]:
import math
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [5]:
from numpy.random import randint as ri
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[3 1 3]
 [3 2 2]
 [9 3 3]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[5 4 4]
 [1 6 3]
 [9 7 9]]


In [24]:
print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))


Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 51


In [25]:
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))



Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [18 22 11]


In [26]:
print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))


Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [14 18 19]


In [27]:
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1,axis=0))


Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 40  72 144]


In [30]:
print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2,axis=1))


Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [105   6  10]


In [31]:
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 5.666666666666667


In [32]:
print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 3.265986323710904


In [34]:
mat1 = np.array(ri(1,100,9)).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)



Modified matrix of random numbers from 1 to 99
 -------------------------------------------------- 
 [[92 51 28]
 [51  4 87]
 [44 68 23]]


In [35]:
print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


Standard deviation of all numbers in the modified matrix, a larger number
 -------------------------------------------------------------------------------- 
 27.534938523740575


In [36]:
print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))



Variance of all numbers in the modified matrix, a larger number
 -------------------------------------------------------------------------------- 
 758.1728395061727


In [37]:
print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



Median of all numbers in the modified matrix
 ------------------------------------------------------------ 
 51.0


###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [40]:
##Solution
mat1 = np.array(ri(1,100,9)).reshape(3,3)
print(mat1)

[[11 77 91]
 [67 56 64]
 [12 63 98]]


In [41]:
mat1.reshape(9,1)

array([[11],
       [77],
       [91],
       [67],
       [56],
       [64],
       [12],
       [63],
       [98]])

### 4.Sort

In [4]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A,kind='mergesort'))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [12 99 39 44 15 94 86  5 71 49]

Here is the sorted vector
 -------------------------------------------------- 
 [ 5 12 15 39 44 49 71 86 94 99]


In [9]:
M = ri(1,100,25).reshape(5,5) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[74 39 51 95 86]
 [11 56 65 66 44]
 [67 42 49 92  9]
 [70 92 94 74 45]
 [92 63 32 43 97]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[39 51 74 86 95]
 [11 44 56 65 66]
 [ 9 42 49 67 92]
 [45 70 74 92 94]
 [32 43 63 92 97]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[11 39 32 43  9]
 [67 42 49 66 44]
 [70 56 51 74 45]
 [74 63 65 92 86]
 [92 92 94 95 97]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [6]:
# Fill the following ***** with appropriate solution.
a=ri(1,100,10)
b=ri(1,100,10)
c=ri(1,100,10)

print("a:", a)
print("b:", b)
print("c:", c)

a: [73 76 70  1 41 79 73 72 10 72]
b: [73  3 10 93  5 19 76 41 81 63]
c: [80 46 69 16 34 46 91 25 48 30]


In [8]:
print("Max of a:", a.max())
print("Max of b:",b.max())

Max of a: 79
Max of b: 93


In [9]:
print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())

Max of a location: 5
Max of b location: 3
Max of c location: 6


In [12]:
print("Max of c:", c.max())


Max of c: 91


In [13]:
print("Max of c location:", c.argmax())

Max of c location: 6


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [10]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


1st Matrix of random single-digit numbers
----------------------------------------
 [[1 7 3]
 [8 5 9]
 [8 3 4]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[3 1 8]
 [1 5 6]
 [7 2 8]]


In [11]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


Sq-root of 1st matrix using np
------------------
 [[1.         2.64575131 1.73205081]
 [2.82842712 2.23606798 3.        ]
 [2.82842712 1.73205081 2.        ]]


In [12]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[2.71828183e+00 1.09663316e+03 2.00855369e+01]
 [2.98095799e+03 1.48413159e+02 8.10308393e+03]
 [2.98095799e+03 2.00855369e+01 5.45981500e+01]]


In [13]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.         0.84509804 0.47712125]
 [0.90308999 0.69897    0.95424251]
 [0.90308999 0.47712125 0.60205999]]


In [14]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))


Modulo reminder using np
 -------------------------------------------------- 
 [[1 0 3]
 [0 0 3]
 [1 1 4]]


### 7.Generating matrices from distributions

In [15]:
print("Random number generation (from Uniform distribution)")
print(np.random.random((2,3))) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 


Random number generation (from Uniform distribution)
[[0.55432806 0.32458363 0.62374898]
 [0.95097182 0.26538166 0.37882166]]


In [16]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.normal(0,1,(3,3)))


Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.06154025  0.12189568  0.30509426]
 [-0.28469632 -0.01637103  0.90912715]
 [-1.55096645 -0.20944223  0.64008984]]


In [18]:
print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)


Random integer vector: [99 52 24 49 88 60 85  6 29 27]

Random integer matrix
[[ 6 20 60 58]
 [39 62 76 10]
 [19 95 21 72]
 [17 91 43 93]]


In [19]:
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw


20 samples drawn from a dice throw: [6 4 3 4 1 1 3 4 4 1 1 5 5 5 5 2 2 2 5 6]


### 8.Find the nearest value from a given number in an array using NumPy.

In [29]:
arr_list = np.array(ri(1,12,5))
value = 10
print(arr_list)
index = (np.abs(arr_list - value)).argmin()
print(index)

[10  2  6  9  8]
0


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [37]:
np.fromfunction(lambda i,j: i*j,(3,3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])